services:
  hexagonal:
    image: mongo:6.0.6
    container_name: hexagonal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: uhexagonal
      MONGO_INITDB_ROOT_PASSWORD: secret123456
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    name: mongodb_hexagonal_data