services:
  app:
    build: .
    container_name: my_app
    restart: always
    ports:
      - 8000:8000
    environment:
      # Server
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - HOSTNAME=${HOSTNAME}
      # MongoDB
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      # Technology
      - TECHNOLOGY=${TECHNOLOGY}
      # Redis
      - REDIS_URL=${REDIS_URL}
      # Security
      - HASH_SALT=${HASH_SALT}
      # JWT
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      - cluster-mongodb
      - cache

  cluster-mongodb:
    image: mongo:6.0.6
    container_name: mongo_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  cache:
    image: redis:bookworm
    container_name: cache_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  mongodb_data:
    name: mongodb_hexagonal_data
  redis_data:
    name: cache_redis_data